### ISSUE TITLE
unexpected use of state object

### ISSUE THREAD

**Issue by r14c** [pushowl/nacelle-pushowl-nuxt-module#7]
https://github.com/pushowl/nacelle-pushowl-nuxt-module/blob/master/lib/nacelle-pushowl-plugin.js#L155

i've been having some issues integrating this module into our storefront. i believe this is partly due to some unexpected choices within `nacelle-pushowl-plugin.js`. some i've been able to adapt to easily, but this use of `$store.state` is throwing me through a loop. my first inclination is to think that line 155 should be `store.getters['product/selectedVariant']`, but that property is never keyed by product handle.

```
    // PRODUCT_VIEW event can fire outside of product pages, so explicitly check for product url
    if (
      type === 'events/addEvent' &&
      payload.eventType === 'PRODUCT_VIEW' &&
      location.pathname.startsWith('/products/')
    ) {
      const variant =
        state[`product/${payload.product.handle}`]?.selectedVariant

      handleProductView(payload.product, variant)
      setFlyoutWidget(true)
      return
    } else {
      // Hide the flyout widget
      setFlyoutWidget(false)
    }
```

the only alternative i can think of that will support this use of `$store.state` is to call `Vue.set` on the root state every time a product is viewed. however, this would create a memory leak because every product view would increase the size of the root state.

any help/guidance you can give is appreciated.

**Comment by chinchang** [comment]
Hi @r14c We are checking this...will update here soon. Meanwhile, can you please confirm if you are using at least version 2.0 of the nacelle nuxt starter? The latest version of this module needs at least 2.0 of nacelle nuxt starter.

**Comment by r14c** [comment]
@chinchang looks like we are on version 1. i'll have to go back and see if i can reproduce this issue on an updated starter. sorry about that!
